title: John's Studio Laboratory
author: John Hendershott
email: jpshott2015@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to a place of peace of mind and relaxation of spirit.  No bugs allowed.
  Email me at [John Hendershott](mailto:jpshott2015@gmail.com) to let me know how awesome this is.

# social links
twitter_username: DontGotOne
github_username:  NotYours

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
